<?php

namespace AppBundle\Repository;

/**
 * CommunesFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunesFrRepository extends \Doctrine\ORM\EntityRepository
{
}
